<?php

    return [
        'admin' => [
            'user'    => [
                'update' => [
                    'name'     => 'required|max:255' , //'email' => 'required|email|max:255|unique:users,email',
                    'password' => 'required|min:6' ,
                    'role_id' => 'required' ,
                ] ,
                'store'  => [
                    'name'     => 'required|max:255' , //'email' => 'required|email|max:255|unique:users',
                    'password' => 'required|min:6' ,
                    'role_id' => 'required' ,
                ] ,
            ] ,
            'role'    => [
                'update' => [
                    'name'         => 'required|max:255' ,
                    'display_name' => 'required|max:255' ,
                ] ,
                'store'  => [
                    'name'         => 'required|max:255|unique:role,name' ,
                    'display_name' => 'required|max:255' ,
                ] ,
            ] ,
            'company' => [
                'update' => [
                    'name'           => 'required' ,
//                    'property'        => 'required' ,
//                    'scale' => 'required' ,
//                    'type' => 'required' ,
//                    'is_ipo' => 'required' ,
                    'com_intro' => 'required' ,
                ] ,
                'store'  => [
                    'name'           => 'required' ,
//                    'property'        => 'required' ,
//                    'scale' => 'required' ,
//                    'type' => 'required' ,
//                    'is_ipo' => 'required' ,
                    'com_intro' => 'required' ,
                ] ,
            ] ,
            'job' => [
                'update' => [
                    'title'           => 'required' ,
                    'salary'        => 'required' ,
                    'hire_count' => 'required' ,
                    'reward' => 'required' ,
                    'industry' => 'required' ,
                    //'education' => 'required' ,
                    //'experience' => 'required' ,
                    //'type' => 'required' ,
                    //'city' => 'required' ,
//                    'address' => 'required' ,
                    //'detail' => 'required' ,
                    'detail_rich_text' => 'required' ,
                    //'company' => 'required' ,
                ] ,
                'store'  => [
                    'title'           => 'required' ,
                    'salary'        => 'required' ,
                    'hire_count' => 'required' ,
                    'industry' => 'required' ,
                    'reward' => 'required' ,
//                    'education' => 'required' ,
//                    'experience' => 'required' ,
//                    'type' => 'required' ,
                    'city' => 'required' ,
//                    'address' => 'required' ,
                    //'detail' => 'required' ,
                    'detail_rich_text' => 'required' ,
                    'com_name' => 'required' ,
                ] ,
            ] ,
            'activity' => [
                'update' => [
                    'name'           => 'required' ,
                    'start_time'        => 'required' ,
                    'end_time' => 'required' ,
                    'sign_up_end_time' => 'required' ,
                    'price' => 'required' ,
                    'address' => 'required' ,
                    //'city' => 'required' ,
                    //'pic' => 'required' ,
                    //'detail' => 'required' ,
                    'forms' => 'required' ,
                    'detail_rich_text' => 'required' ,
                ] ,
                'store'  => [
                    'name'           => 'required' ,
                    'start_time'        => 'required' ,
                    'end_time' => 'required' ,
                    'sign_up_end_time' => 'required' ,
                    'price' => 'required' ,
                    'address' => 'required' ,
                    'city' => 'required' ,
                    'pic' => 'required' ,
                    //'detail' => 'required' ,
                    'forms' => 'required' ,
                    'detail_rich_text' => 'required' ,
                ] ,
            ] ,
            'requirement' => [
                'update' => [
                    'company_name'           => 'required' ,
                    'industry'        => 'required' ,
                    'location' => 'required' ,
                    'property' => 'required' ,
                    'employee_number' => 'required' ,
                    'manager_number' => 'required' ,
                    'higher_class_number' => 'required' ,
                    'middle_class_number' => 'required' ,
                    'junior_class_number' => 'required' ,
                    'type' => 'required' ,
                    'classification' => 'required' ,
                    'patent' => 'required' ,
                    'appraise' => 'required' ,
                    'introduce' => 'required' ,
                    'cooperate' => 'required' ,
                    'entrust' => 'required' ,
                    'other' => 'required' ,
                    'budget' => 'required' ,
                    'detail' => 'required' ,
                    'contact' => 'required' ,
                    'phone' => 'required' ,
                    'com_intro' => 'required' ,
                    'requirement_number' => 'required' ,
                    'problem_number' => 'required' ,
                ] ,
                'store'  => [
                    'company_name'           => 'required' ,
                    'industry'        => 'required' ,
                    'location' => 'required' ,
                    'property' => 'required' ,
                    'employee_number' => 'required' ,
                    'manager_number' => 'required' ,
                    'higher_class_number' => 'required' ,
                    'middle_class_number' => 'required' ,
                    'junior_class_number' => 'required' ,
                    'type' => 'required' ,
                    'classification' => 'required' ,
                    'patent' => 'required' ,
                    'appraise' => 'required' ,
                    'introduce' => 'required' ,
                    'cooperate' => 'required' ,
                    'entrust' => 'required' ,
                    'other' => 'required' ,
                    'budget' => 'required' ,
                    'detail' => 'required' ,
                    'contact' => 'required' ,
                    'phone' => 'required' ,
                    'com_intro' => 'required' ,
                    'requirement_number' => 'required' ,
                    'problem_number' => 'required' ,
                ] ,
            ] ,
            'recommend' => [
                'update' => [
                    //'status'           => 'required' ,
                    'is_handle' => 'required' ,
                ] ,
                'store'  => [
                    //
                ] ,
            ] ,
            'talent' => [
                'update' => [
                    'name' => 'required' ,
                    'major' => 'required' ,
                    'phone' => 'required' ,
                    'if_contact' => 'required' ,
                    //'if_resume' => 'required' ,
                    'school' => 'required' ,
                    'email' => 'required' ,
                ] ,
                'store'  => [
                    'name' => 'required' ,
                    'major' => 'required' ,
                    'phone' => 'required' ,
                    'if_contact' => 'required' ,
                    //'if_resume' => 'required' ,
                    'school' => 'required' ,
                    'email' => 'required' ,
                ] ,
            ] ,
            'update_log' => [
                'update' => [
                    //
                ] ,
                'store'  => [
                    'author' => 'required' ,
                    'content' => 'required' ,
                ] ,
            ] ,
        ] ,
    ];